apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.AppVersion }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        version: {{ .Chart.AppVersion }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 60010

          # 환경변수 추가 
          env:
            - name: AWS_REGION
              value: {{ .Values.env.aws.region }}
            - name: AGENT
              value: {{ .Values.env.agent }}
            - name: AGENT_ID
              value: {{ .Values.env.agentId }}
            - name: AGENT_ALIAS 
              value: {{ .Values.env.agentAlias }}
            - name: AGENT_KMS_ARN
              value: {{ .Values.env.agentKmsArn }}
            - name: SESSION
              value: {{ .Values.env.sessionId }}

          # secret 불러오기
          envFrom:
            - secretRef:
                name: agent-service-secrets

          # 헬스체크 추가
          {{- if .Values.healthCheck.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.healthCheck.port }}
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.healthCheck.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}

          # 리소스 제한 (권장)
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}