replicaCount: 1

image:
  repository: 026274465258.dkr.ecr.ap-northeast-2.amazonaws.com/agent-service
  tag: 20250605-893e168
  pullPolicy: IfNotPresent    # 이미지 가져오는 정책 로컬에 없을 때만 pull

service:
  type: ClusterIP   # 클러스터 내부에서만 접근 가능 (기본값)
  port: 80

# 헬스체크 설정 (권장)
healthCheck:
  enabled: true
  path: /health
  port: 60010
  initialDelaySeconds: 60
  periodSeconds: 10

env:
  aws:
    region: ap-northeast-2
  agent: modive-agent
  agentId: FDIYLCYEO3
  agentAlias: TSTALIASID
  agentKmsArn: arn:aws:kms:ap-northeast-2:026274465258:key/04393036-0a55-4ab8-afc6-8563d71c49d4
  sessionId: 8cf7166d-db49-409a-b5ef-811bc4debfe1