version: '3'

services:
  web:
    build: .
    image: modive-agent:latest
    container_name: agent-service
    ports:
      - "60010:60010"
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    restart: always
    networks:
      - modive-network

networks:
  app-network:
    driver: bridge